name: Release Archive

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: check doxygen
        version: 1.0

    - name: autoconf
      run: autoreconf -i

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck

    - name: version
      #run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
      run: echo "::set-output name=version::1.0.0"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: ChangeLog
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./test-${{ steps.version.outputs.version }}.tar.gz
        asset_name: test-${{ steps.version.outputs.version }}.tar.gz
        asset_content_type: application/gzip

